# .github/workflows/your-workflow-name.yml

name: Hardhat Tests

# Controls when the workflow will run
on: [push]

jobs:
  test-contracts:
    name: Run Hardhat Tests
    runs-on: ubuntu-latest

    # This 'env' block makes the secret available as an environment variable
    # for all steps in this job.
    env:
      DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: contracts/yarn.lock

      - name: Install dependencies in contracts folder
        working-directory: ./contracts
        run: yarn install --frozen-lockfile

      - name: Run Hardhat tests
        # The DEPLOYER_PRIVATE_KEY is now available to this command
        working-directory: ./contracts
        run: npx hardhat test